---
version: 1
disable_existing_loggers: False
formatters:
  raw:
    format: "%(message)s"
  simple:
    format: "[%(name)s][%(levelname)s][%(asctime)s]  %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: raw
    stream: ext://sys.stdout

  single_variable_file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: single_variable.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

  rabbitbear_file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: rabbitbear.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

loggers:
  single_variable:
    level: INFO
    handlers: [console, single_variable_file]
    propagate: no

  rabbitbear:
    level: INFO
    handlers: [rabbitbear_file]
    propagate: no

root:
  level: INFO
  handlers: [console]
...