---
version: 1
disable_existing_loggers: False
formatters:
  raw:
    format: "%(message)s"
  simple:
    format: "[%(name)s][%(levelname)s][%(asctime)s]  %(message)s"

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: raw
    stream: ext://sys.stdout

  linear_file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: linear_regression.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

  rabbitbear_file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: simple
    filename: rabbitbear.log
    maxBytes: 10485760 # 10MB
    backupCount: 20
    encoding: utf8

loggers:
  linear_regression:
    level: DEBUG
    handlers: [console, linear_file]
    propagate: no

  rabbitbear:
    level: DEBUG
    handlers: [rabbitbear_file]
    propagate: no

root:
  level: INFO
  handlers: [console]
...